### ISSUE TITLE
Error uploading app to Shinyapp.io

### ISSUE THREAD

**Issue by fischert00** [GIScience/openrouteservice-r#73]
I created an shiny app using the ORS package and it works just fine on my laptop but when I upload it to Shinyapp.io I get the following:

Error in value[[3L]](cond) : 
  The 'system' keyring does not exists, create it first!
Calls: local ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted

Also, this app used to upload just fine until I added the ORS package and functionality.  Any help is appreciated.

Thanks, Tom...

**Comment by aoles** [comment]
Hi Tom,

Thanks for reaching out!

The error comes from the the system's keyring infrastructure used to store the ORS API secret. While this approach typically works fine locally,  when deploying at shinyapps.io the recommended way to provide the secret is through a file named .Renviron located in your app's directory and containing the following line:

`ORS_API_KEY=<your api key>`

where you should replace `<your api key>` with your actual API key. In case you make the source code available in a public repo such as GitHub or similar make sure you don't include this file, otherwise the key would become compromised. When using git you can exclude the file from versioning by listing it in the .gitignore file.

Let me know in case something is unclear or if you have any further questions.

Cheers,
Andrzej

**Comment by fischert00** [comment]
Thanks, that fixed it and it working now.  Appreciate the quick reply.

Tom...
