### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by cbeesonlynch** [GIScience/openrouteservice-r#77]
I cannot install the package at all. Using R Studio 2023.03.1 on Windows. 

![image](https://github.com/GIScience/openrouteservice-r/assets/113363827/2864b8b3-36bb-46c0-b8b7-31b034dd4643)

**Comment by MichaelsJP** [comment]
@cbeesonlynch Thanks for opening the issue.
@aoles Do you know what could have caused this?

**Comment by aoles** [comment]
Dear @cbeesonlynch ,

Thanks for reaching out! I don't observe this on other systems and I have no idea what could be the problem here. Maybe try executing `devtools::install_github("GIScience/openrouteservice-r")` from your R console rather than within an R Markdown document to see whether this helps?
